version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:30"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
  - ryanjwilke
  assignees:
  - ryanjwilke
  labels:
  - dependencies
  ignore:
  - dependency-name: html-validate
    versions:
    - 4.10.0
    - 4.3.0
    - 4.4.0
    - 4.5.0
    - 4.6.0
    - 4.6.1
    - 4.7.0
    - 4.7.1
    - 4.8.0
    - 4.9.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-router"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-unit-jest"
    versions:
    - 4.5.11
  - dependency-name: lint-staged
    versions:
    - 10.5.3
